In [137]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [138]:
data=pd.read_csv('Churn_Modelling.csv')
data

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [139]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [140]:
#preprocess the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [141]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [142]:
#Encode the categorical Variable
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [143]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [144]:
#onehot encode geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder(sparse_output=False)
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [145]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [146]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [147]:
geo_encoder_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [148]:
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [149]:
#combine 
data=pd.concat([data.drop('Geography',axis=1),geo_encoder_df],axis=1)

In [150]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [151]:
#save the encoders and scaler for future use ;)
with open('label_encoder_gender.pkl','wb') as file :
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb') as file :
    pickle.dump(onehot_encoder_geo,file)

In [152]:
#dependent and independent features
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [153]:
X=data.drop('Exited',axis=1)
Y=data['Exited']

In [154]:
X

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 12 columns]

In [155]:
Y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [156]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [157]:
X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [158]:
with open('scaler.pkl','wb') as file :
    pickle.dump(scaler,file)

In [159]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [160]:
#ANN IMPLEMNTATION
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [161]:
X_train.shape

(8000, 12)

In [162]:
#model building
model=Sequential([
    Dense(62,activation='relu',input_shape=(X_train.shape[1],)), #first hidden layer
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid') #o/p layer
]
)

In [163]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 62)                806

 dense_7 (Dense)             (None, 32)                2016

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2855 (11.15 KB)
Trainable params: 2855 (11.15 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [164]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
#to give Adam learning rate acc to myself
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [165]:
#compile the model
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [166]:
#setup the tensorboard
import tensorflow
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
#tensorboard helps in visualizing the model training and performance metrics in real time
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [167]:
##set up early stopping to prevent overfitting 
#selecting most relevent epocs
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [168]:
#train the model
history=model.fit(
    X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 154.4878 - accuracy: 0.6768 - val_loss: 61.3891 - val_accuracy: 0.6685
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 125.4241 - accuracy: 0.6736 - val_loss: 84.9296 - val_accuracy: 0.8035
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 106.3128 - accuracy: 0.6727 - val_loss: 132.8745 - val_accuracy: 0.8035
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 101.4847 - accuracy: 0.6760 - val_loss: 130.3437 - val_accuracy: 0.7680
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 81.3828 - accuracy: 0.6824 - val_loss: 22.8192 - val_accuracy: 0.7625
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 101.0812 - accuracy: 0.6751 - val_loss: 245.9137 - val_accuracy: 0.4530
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 92.4505 - accuracy: 0.6858 - val_loss: 83.9660 - val_accuracy: 0.8035
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 77.2270 - accuracy: 0.6781 - val_loss: 192.3740 - val_accuracy: 0.8040
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 73.6860 - accuracy: 0.6815 - val_loss: 77.7583 - val_accuracy: 0.3235
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 68.1305 - accuracy: 0.6815 - val_loss: 42.2974 - val_accuracy: 0.8040
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 68.0432 - accuracy: 0.6798 - val_loss: 45.2417 - val_accuracy: 0.5825
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 78.9354 - accuracy: 0.6820 - val_loss: 57.4918 - val_accuracy: 0.8040
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 72.5254 - accuracy: 0.6855 - val_loss: 50.3278 - val_accuracy: 0.6335
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 70.3584 - accuracy: 0.6826 - val_loss: 46.4118 - val_accuracy: 0.8040
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 64.9342 - accuracy: 0.6796 - val_loss: 10.7211 - val_accuracy: 0.7105
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 85.3026 - accuracy: 0.6814 - val_loss: 100.0758 - val_accuracy: 0.8035
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 81.6866 - accuracy: 0.6880 - val_loss: 87.9563 - val_accuracy: 0.8010
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 59.3713 - accuracy: 0.6821 - val_loss: 41.0626 - val_accuracy: 0.5880
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 64.3103 - accuracy: 0.6816 - val_loss: 31.0390 - val_accuracy: 0.7960
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 57.1964 - accuracy: 0.6776 - val_loss: 18.0111 - val_accuracy: 0.7945
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 68.4538 - accuracy: 0.6856 - val_loss: 41.5192 - val_accuracy: 0.8010
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 60.3663 - accuracy: 0.6814 - val_loss: 30.9559 - val_accuracy: 0.6375
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 57.3498 - accuracy: 0.6810 - val_loss: 74.7478 - val_accuracy: 0.8040
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 40.3666 - accuracy: 0.6776 - val_loss: 73.5296 - val_accuracy: 0.2075
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49.1797 - accuracy: 0.6768 - val_loss: 112.1281 - val_accuracy: 0.8040

In [169]:
model.save('model.h5')

d:\Customer Chrun\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [170]:
#load tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [171]:
%reload_ext tensorboard

In [172]:
%tensorboard --logdir logs/fit20260830-205005

Reusing TensorBoard on port 6007 (pid 27400), started 0:04:09 ago. (Use '!kill 27400' to kill it.)

In [ ]:
#load the pickle file